config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "tasks", to: "task#list"
  get "tasks/new", to: "task#new"
  get "tasks/:id/edit", to: "task#edit", as: :edit
  get "tasks/:id", to: "task#show", as: :task
  post "tasks", to: "task#create"
  patch "tasks/:id", to: "task#update"
  delete "tasks/:id", to: "task#destroy"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/task_controller.rb
class TaskController < ApplicationController
  def list
   @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.create(task_params)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path, status: :see_other
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/task/edit.html.erb
<%= form_with model: @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.check_box :completed %>
  <%= f.label :completed %>
  <%= f.submit %>
<% end %>

app/views/task/list.html.erb
<h1>Your list</h1>
<ul>
<% @tasks.each do |item|%>
  <span> <%= check_box_tag "", item.completed, item.completed %> </span>
 <li><%= link_to item.title, task_path(item) %></li>
<%end%>
</ul>

<%= link_to "Add a new task", tasks_new_path %>

app/views/task/new.html.erb
<%= form_with model: @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.check_box :completed %>
  <%= f.label :completed %>
  <%= f.submit %>
<% end %>

app/views/task/show.html.erb
<h1> Task: <%= @task.title %> </h1>
<p> Note: <%= @task.details %> </p>
<p> completed?: <%= @task.completed %> </p>
<p> <%= link_to "Edit this task", edit_path %></p>
<p> <%= link_to "Back to all tasks", tasks_path %></p>
<%= link_to "Delete",
  task_path(@task),
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
%>